### ISSUE TITLE
Pokemon Based Jokes

### ISSUE THREAD

**Issue by koaning** [RasaHQ/pokedex-demo#3]
I will add some jokes based on pokemon. Here's the current shortlist. Should I add more? 

```
  utter_joke:
    - text: Are you sure you can handle my jokes? You might laugh your Ash off.
    - text: Why did the Squirtle cross the road? To get to the other tide!
    - text: What appears over Ash’s head when he gets an idea? A LightBulbasaur
    - text: Where did Brock take Nurse Joy for a date? The PokeBall
    - text: What’s better than one Pikachu? PikaTWO
    - text: What does Moeowth see when it looks in the mirror? A copy-cat!
    - text: When does a Gastly eat breakfast? In the moaning.
    - text: Which Pokemon does Dracula like most? Koffin'
```
